# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-162829284-3'


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link: 'mailto:vas.cripto.investimento@gmail.com'}
- {icon: 'instagram', link: 'https://instagram.com/vas.cripto.investimento'}


# Customize site text
title: "V.A.S - Compra e venda de criptomoedas"
header: ""